# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 2 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# only does tests at the moment, and i added sklearn deprecated because this often causes issues. 
# it shouldnt really be in use currently i think because free accounts dont have runners so pipelines are poop. but BIF might give runners?


image: python:3.12
variables:
  SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: "True"
  
stages:
    - static
    - unit

lint-test-job:   # This job also runs in the static stage.
  stage: static    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "running pre-commit hooks to ensure code quality."
    - pip install black
    - pip install ruff
    - black .
    - ruff check --fix --exit-non-zero-on-fix
    - echo "No lint issues found."


unit-test-job:   # This job runs in the unit stage.
  stage: unit    # It only starts when the job in the build stage completes successfully.
  image: python:3.12
  script:
    - echo "setting up testing enviroment"
    - pip install pytest pytest-cov
    - echo "into requirements"
    - pip install --upgrade pip
    - pip install --upgrade setuptools wheel
    - echo "installing requirements, this might take a while"
    - pip install -r requirements.txt
    - python -m pytest --cov-report=html --cov=leiden_intern_template
    - echo "testing done"
  artifacts:
    paths:
      - coverage
    expire_in: 30 days
